### ISSUE TITLE
Only first image showing

### ISSUE THREAD

**Issue by sanrooney** [ludovicroland/carousel-android#3]
firstly added image only appearing on the view. Seems the holder is added i can slide the circular but no image are loaded. 1/4 is showing. As Attached below.

![screenshot_2015-05-20-17-27-52](https://cloud.githubusercontent.com/assets/5004079/7722758/d44d5998-ff15-11e4-87e5-1a9f0e01f218.png)
![screenshot_2015-05-20-17-27-48](https://cloud.githubusercontent.com/assets/5004079/7722759/d4767ca6-ff15-11e4-8540-f4df8f3b0cd3.png)
![screenshot_2015-05-20-17-27-43](https://cloud.githubusercontent.com/assets/5004079/7722760/d4d0ad34-ff15-11e4-93f8-819ed1f86789.png)

**Comment by ludovicroland** [comment]
Hi @sanrooney !

Thx for your feedback. It is possible to have more information about your source code like :
- the activity/fragment layout
- the item layout
- the source code that adds the images to the carousel

Thx !

**Comment by sanrooney** [comment]
Ok i use a 
fragment layout

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/main_bg_color">

    <fr.rolandl.carousel.Carousel
        android:id="@+id/carousel"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:animationDuration="100"
        android:gravity="center|top"/>

</RelativeLayout>
```

item layout

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent" >

    <ImageView
        android:id="@+id/image"
        android:layout_width="350dp"
        android:layout_height="200dip"
        android:layout_margin="5dp"
        android:adjustViewBounds="true"
        android:scaleType="fitCenter"
        android:layout_gravity="center"
        />

    <TextView
        android:id="@+id/name"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textColor="@android:color/black"
        android:text="Card"
        android:layout_gravity="center"
        />
</LinearLayout>

```

source code as in sample : 

```
                View rootView = inflater.inflate(R.layout.fragment_member_card, container, false);
        carousel = (Carousel) rootView.findViewById(R.id.carousel);

        List<cards> card = new ArrayList<>();
        card.add(new cards("Supp Card", "bigbang"));
        card.add(new cards("Junior Card", "game_of_thrones"));
        card.add(new cards("Primary Card", "hannibal"));
        card.add(new cards("Supp Card", "house"));

        adapter = new Cards_Adapter(getActivity(), card);
        carousel.setAdapter(adapter);
        adapter.notifyDataSetChanged();
```

Thanks for your reply.

**Comment by ludovicroland** [comment]
@sanrooney ,

Thx, I'm going to check that ASAP.

**Comment by sanrooney** [comment]
ok thank you. Waiting for your update.

**Comment by sanrooney** [comment]
Hi, is this library supported on Jellybean 4.1.2?
I tested this on another device which running jellybean samsung GT-I9100 and it crash when slide.
Logcat error :-

05-21 12:13:33.685  21621-21621/com.appandus.cex E/InputEventReceiver﹕ Exception dispatching input event.
05-21 12:13:33.685  21621-21621/com.appandus.cex E/MessageQueue-JNI﹕ Exception in MessageQueue callback: handleReceiveCallback
05-21 12:13:33.700  21621-21621/com.appandus.cex E/MessageQueue-JNI﹕ java.lang.NullPointerException
            at fr.rolandl.carousel.CarouselSpinner.pointToPosition(CarouselSpinner.java:269)
            at fr.rolandl.carousel.Carousel.onDown(Carousel.java:782)
            at android.view.GestureDetector.onTouchEvent(GestureDetector.java:1340)
            at fr.rolandl.carousel.Carousel.onTouchEvent(Carousel.java:965)
            at android.view.View.dispatchTouchEvent(View.java:7350)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2412)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2147)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2134)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1471)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2487)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2082)
            at android.view.View.dispatchPointerEvent(View.java:7535)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3415)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3347)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4456)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4434)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4538)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:125)
            at android.os.Looper.loop(Looper.java:124)
            at android.app.ActivityThread.main(ActivityThread.java:4921)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
            at dalvik.system.NativeStart.main(Native Method)
05-21 12:13:33.720  21621-21621/com.appandus.cex E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NullPointerException
            at fr.rolandl.carousel.CarouselSpinner.pointToPosition(CarouselSpinner.java:269)
            at fr.rolandl.carousel.Carousel.onDown(Carousel.java:782)
            at android.view.GestureDetector.onTouchEvent(GestureDetector.java:1340)
            at fr.rolandl.carousel.Carousel.onTouchEvent(Carousel.java:965)
            at android.view.View.dispatchTouchEvent(View.java:7350)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2412)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2147)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2134)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1471)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2487)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2082)
            at android.view.View.dispatchPointerEvent(View.java:7535)
            at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3415)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3347)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4456)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4434)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4538)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:125)
            at android.os.Looper.loop(Looper.java:124)
            at android.app.ActivityThread.main(ActivityThread.java:4921)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by mokai** [comment]
My side as well

**Comment by ludovicroland** [comment]
@sanrooney : I cannot reproduce the issue. What is the size in pixels of the images you are trying to display ?

I opened another issue for the crash on jellybean : https://github.com/ludovicroland/carousel-android/issues/4

**Comment by sanrooney** [comment]
Hi, good to hear from you.. I used 878 x 557 size in pixel images... All 3 images i used are same pixels.

**Comment by anjawahl** [comment]
Hi, i'm having the same issue. It occurs especially if i update my adapter (set a new one). Did you find a solution or a workaround?

**Comment by anjawahl** [comment]
found the solution on http://www.codeproject.com/Articles/146145/Android-D-Carousel:

"Resolve by adding this line-

carousel.setSelection(0, true);"

worked for me :)

**Comment by aminrezaee** [comment]
i found the problem for exception sanrooney refered. the problem is that carousel constructors are not complete . one of them is complete. you should just copy the code inside of complete one and paste it into other constructors.

**Comment by ziacto** [comment]
i am facing the same one image showing issue in my Fragment layout. Can you fix this please. Thanks
<img width="404" alt="screenshot of google chrome 6-21-16 1 46 20 pm" src="https://cloud.githubusercontent.com/assets/2651025/16225206/8dc2ae58-37b6-11e6-9807-b8e5ed361fb5.png">
But in Activity i can see 3 images. 
<img width="397" alt="screenshot of google chrome 6-21-16 1 47 03 pm" src="https://cloud.githubusercontent.com/assets/2651025/16225236/a6276894-37b6-11e6-9bb3-501add6a41ce.png">

I dont know why this solved by just adding this line 
carousel.setSelection(0, true); :)
