### ISSUE TITLE
Is this library supported on Jellybean 4.1.2?

### ISSUE THREAD

**Issue by ludovicroland** [ludovicroland/carousel-android#4]
Hi, is this library supported on Jellybean 4.1.2?
I tested this on another device which running jellybean samsung GT-I9100 and it crash when slide.
Logcat error :-

05-21 12:13:33.685 21621-21621/com.appandus.cex E/InputEventReceiver﹕ Exception dispatching input event.
05-21 12:13:33.685 21621-21621/com.appandus.cex E/MessageQueue-JNI﹕ Exception in MessageQueue callback: handleReceiveCallback
05-21 12:13:33.700 21621-21621/com.appandus.cex E/MessageQueue-JNI﹕ java.lang.NullPointerException
at fr.rolandl.carousel.CarouselSpinner.pointToPosition(CarouselSpinner.java:269)
at fr.rolandl.carousel.Carousel.onDown(Carousel.java:782)
at android.view.GestureDetector.onTouchEvent(GestureDetector.java:1340)
at fr.rolandl.carousel.Carousel.onTouchEvent(Carousel.java:965)
at android.view.View.dispatchTouchEvent(View.java:7350)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2412)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2147)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2134)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1471)
at android.app.Activity.dispatchTouchEvent(Activity.java:2487)
at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2082)
at android.view.View.dispatchPointerEvent(View.java:7535)
at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3415)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3347)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4456)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4434)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4538)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:125)
at android.os.Looper.loop(Looper.java:124)
at android.app.ActivityThread.main(ActivityThread.java:4921)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
at dalvik.system.NativeStart.main(Native Method)
05-21 12:13:33.720 21621-21621/com.appandus.cex E/AndroidRuntime﹕ FATAL EXCEPTION: main
java.lang.NullPointerException
at fr.rolandl.carousel.CarouselSpinner.pointToPosition(CarouselSpinner.java:269)
at fr.rolandl.carousel.Carousel.onDown(Carousel.java:782)
at android.view.GestureDetector.onTouchEvent(GestureDetector.java:1340)
at fr.rolandl.carousel.Carousel.onTouchEvent(Carousel.java:965)
at android.view.View.dispatchTouchEvent(View.java:7350)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2412)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2147)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2418)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2119)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2134)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1471)
at android.app.Activity.dispatchTouchEvent(Activity.java:2487)
at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:59)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2082)
at android.view.View.dispatchPointerEvent(View.java:7535)
at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3415)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3347)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4456)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4434)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4538)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:125)
at android.os.Looper.loop(Looper.java:124)
at android.app.ActivityThread.main(ActivityThread.java:4921)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
at dalvik.system.NativeStart.main(Native Method)

**Comment by ludovicroland** [comment]
I tried the sample app on a Nexus 4 on Android 4.1.1. It works. I am going to try on a Samsung Galaxy S 2 on Android 4.1.2 on next week.
